//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonsAtDayForTeacher
    {
        public string Предмет { get; set; }
        public short Номер_урока { get; set; }
        public System.TimeSpan Время_начала_урока { get; set; }
        public System.TimeSpan Время_завершения_урока { get; set; }
    }
}
