//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSchedule.Model
{
	using System;
	using System.Collections.Generic;
	
	public partial class Group
	{
		public Group()
		{
			this.Lesson = new HashSet<Lesson>();
			this.Student = new HashSet<Student>();
			this.Teacher = new HashSet<Teacher>();
		}
		public Group(int year, string name)
		{
			Year = year;
			Name = name;
		}
	
		public int Id { get; set; }
		public int Year { get; set; }
		public string Name { get; set; }
	
		public virtual ICollection<Lesson> Lesson { get; set; }
		public virtual ICollection<Student> Student { get; set; }
		public virtual ICollection<Teacher> Teacher { get; set; }
	}
}
