//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSchedule.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.ClassTeacher = new HashSet<ClassTeacher>();
            this.Schedule = new HashSet<Schedule>();
            this.SpecialityTeacher = new HashSet<SpecialityTeacher>();
            this.TeacherPhone = new HashSet<TeacherPhone>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
    
        public virtual ICollection<ClassTeacher> ClassTeacher { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual ICollection<SpecialityTeacher> SpecialityTeacher { get; set; }
        public virtual ICollection<TeacherPhone> TeacherPhone { get; set; }
    }
}
